Feature/ab#645 integrate new version of keycloak
starwit/helm-charts pull request #6
Opened 2023-05-21 16:12 UTC by DerCed

2023-05-21 16:13 UTC, DerCed commented
Missing: Realm in configmap

2023-06-21 11:04 UTC, witchpou requested changes
It needs to be clarify, why readiness, startup and liveness probes are deleted.

2023-06-21 11:13 UTC, witchpou commented on charts/cityos/Chart.yaml
> -    repository: https://codecentric.github.io/helm-charts
sehr schön

2023-06-21 12:11 UTC, DerCed commented
> It needs to be clarify, why readiness, startup and liveness probes are deleted.

Is enabled by default by the keycloak helm chart:

![image](https://github.com/starwit/helm-charts/assets/16734873/6f96d446-cf74-4c91-b128-416986ddfd96)

2023-06-21 13:49 UTC, witchpou approved these changes

2023-06-21 19:57 UTC, merged